//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doanh_so
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngay_ct { get; set; }
        public string ten_kh { get; set; }
        public Nullable<decimal> doanh_so { get; set; }
    }
}
